CREATE DATABASE CAP_PROJ_MY_MOVIE_PLAN;

USE CAP_PROJ_MY_MOVIE_PLAN;

CREATE TABLE USER_CONFIG (
    USER_ID             VARCHAR(20)		NOT NULL,
    FIRST_NAME			VARCHAR(30)		NOT NULL,
	MIDDLE_NAME			VARCHAR(30),
	LAST_NAME		    VARCHAR(30)     NOT NULL,
	EMAIL				VARCHAR(50)		NOT NULL,
    PASSWORD            VARCHAR(15)		NOT NULL,
    IS_ADMIN            BOOL            NOT NULL,
    CONSTRAINT PK_USER_CFG PRIMARY KEY (USER_ID)
);

CREATE INDEX IDX_USER_CFG_01 ON USER_CONFIG (EMAIL);

CREATE TABLE MOVIE_GENRE (
    GENRE_CODE      VARCHAR(15)	    NOT NULL,
    GENRE_NAME      VARCHAR(50)	    NOT NULL,
    DESCRIPTION     VARCHAR(128), 
    CONSTRAINT PK_MOVIE_GEN PRIMARY KEY (GENRE_CODE)
);

CREATE TABLE MOVIE_LANG (
    LANG_CODE       VARCHAR(10)	    NOT NULL,
    LANG_NAME       VARCHAR(50)	    NOT NULL,
    DESCRIPTION     VARCHAR(128), 
    CONSTRAINT PK_MOVIE_LANG PRIMARY KEY (LANG_CODE)
);

CREATE TABLE MOVIES (
    MOVIE_ID        MEDIUMINT 		NOT NULL AUTO_INCREMENT,
    GENRE_CODE      VARCHAR(15)     NOT NULL,
    LANG_CODE       VARCHAR(10)     NOT NULL,
    MOVIE_NAME      VARCHAR(75)		NOT NULL,
    DESCRIPTION     VARCHAR(256),
    STARRING        VARCHAR(128),
    DIRECTED_BY     VARCHAR(80)     NOT NULL,
    MOVIE_PIC_PATH  VARCHAR(128),
    TICKET_PRICE    FLOAT			NOT NULL,
    IS_ACTIVE       CHAR(1)         NOT NULL,
    CONSTRAINT PK_PRODUCT PRIMARY KEY (MOVIE_ID),
    CONSTRAINT FK_MOVIE_01  FOREIGN KEY (GENRE_CODE)    REFERENCES MOVIE_GENRE   (GENRE_CODE),
    CONSTRAINT FK_MOVIE_02  FOREIGN KEY (LANG_CODE)     REFERENCES MOVIE_LANG    (LANG_CODE)    
);

CREATE INDEX IDX_MOVIE_01 ON MOVIES (GENRE_CODE, IS_ACTIVE);
CREATE INDEX IDX_MOVIE_02 ON MOVIES (LANG_CODE, IS_ACTIVE);
CREATE INDEX IDX_MOVIE_03 ON MOVIES (MOVIE_NAME, IS_ACTIVE);
CREATE INDEX IDX_MOVIE_04 ON MOVIES (STARRING, IS_ACTIVE);
CREATE INDEX IDX_MOVIE_05 ON MOVIES (DIRECTED_BY, IS_ACTIVE);
CREATE INDEX IDX_MOVIE_06 ON MOVIES (IS_ACTIVE);

CREATE TABLE MOVIE_SHOW_TIMES
(
    SHOW_TIME_ID        MEDIUMINT 		NOT NULL AUTO_INCREMENT,
    MOVIE_ID            MEDIUMINT 		NOT NULL,
    SHOW_TIME           TIME            NOT NULL,
    CONSTRAINT PK_MOV_SHOW_TIMES PRIMARY KEY (SHOW_TIME_ID),
    CONSTRAINT FK_SHOW_TIMES FOREIGN KEY (MOVIE_ID) REFERENCES MOVIES (MOVIE_ID)
);

CREATE INDEX IDX_SHOW_TIMES_01 ON MOVIE_SHOW_TIMES (MOVIE_ID);

CREATE TABLE PURCHASE (
    PURCHASE_ID     MEDIUMINT 		NOT NULL AUTO_INCREMENT,
    USER_ID         VARCHAR(20)		NOT NULL,
    TOTAL_PRICE     FLOAT           NOT NULL,
    CONSTRAINT PK_PURCHASE PRIMARY KEY (PURCHASE_ID),
    CONSTRAINT FK_PURCHASE FOREIGN KEY (USER_ID) REFERENCES USER_CONFIG (USER_ID)
);

CREATE INDEX IDX_PURCHASE_01 ON PURCHASE (USER_ID);

CREATE TABLE PURCHASE_ITEMS (
    PURCHASE_ITEM_ID    MEDIUMINT 		NOT NULL AUTO_INCREMENT,
    PURCHASE_ID         MEDIUMINT 		NOT NULL,
    MOVIE_ID            MEDIUMINT 		NOT NULL,
    SHOW_TIME           TIME            NOT NULL,
    QUANTITY            SMALLINT        NOT NULL,
    CONSTRAINT PK_PURCHASE_ITEMS PRIMARY KEY (PURCHASE_ITEM_ID),
    CONSTRAINT FK_PURCHASE_ITEMS_01 FOREIGN KEY (PURCHASE_ID) REFERENCES PURCHASE (PURCHASE_ID),
    CONSTRAINT FK_PURCHASE_ITEMS_02 FOREIGN KEY (MOVIE_ID) REFERENCES MOVIES (MOVIE_ID)
);

CREATE INDEX IDX_PURCHASE_ITEMS_01 ON PURCHASE_ITEMS (PURCHASE_ID);
CREATE INDEX IDX_PURCHASE_ITEMS_02 ON PURCHASE_ITEMS (MOVIE_ID);
